name: "Create Node PR"

on:
  workflow_dispatch:
    inputs:
      spec:
        description: "The npm spec to create the PR from"
        required: true
        default: 'latest'
      dryRun:
        description: "Setting this to anything will run all the steps except opening the PR"

jobs:
  create-pull-request:
    {{> job jobName="Create Node PR" }}
      - name: Checkout Node
        uses: actions/checkout@v3
        with:
          token: $\{{ secrets.NODE_PULL_REQUEST_TOKEN }}
          repository: nodejs/node
          fetch-depth: 0
          path: node
      - name: Create Node Pull Request
        env:
          GITHUB_TOKEN: $\{{ secrets.NODE_PULL_REQUEST_TOKEN }}
        run: |
          DRY_RUN=$([ -z "$\{{ inputs.dryRun }}" ] && echo "" || echo "--dry-run")
          node scripts/create-node-pr.js "$\{{ inputs.spec }}" "$DRY_RUN"
